stages:
  - build

minimum:
  stage: build
  image: python
  script:
    - curl -Os http://ece13-grading.acad.ucsc.edu/cicd/fall2024/CIFileExistenceCheck.py
    - curl -Os ${TESTING_BASE_URL}/${TESTING_QUARTER}/CIFileExistenceCheck.py    
    - curl -Os ${TESTING_BASE_URL}/${TESTING_QUARTER}/massPullOptions.cfg
    - curl -Os ${TESTING_BASE_URL}/${TESTING_QUARTER}/currentLab    
    - python3 CIFileExistenceCheck.py massPullOptions.cfg currentLab
  artifacts:
    expire_in: 1 week

