stages:
  - build

minimum:
  stage: build
  image: python
  script:
    - export
    - echo ${TESTING_BASE_URL}
    - echo ${TESTING_QUARTER}
    - curl -O ${TESTING_BASE_URL}/${TESTING_QUARTER}/CIFileExistenceCheck.py    
    - curl -O ${TESTING_BASE_URL}/${TESTING_QUARTER}/massPullOptions.cfg
    - curl -O ${TESTING_BASE_URL}/${TESTING_QUARTER}/currentLab    
    - python3 CIFileExistenceCheck.py massPullOptions.cfg currentLab
  artifacts:
    expire_in: 1 week

